src/SYCH/Controllers/IdeasController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using SYCH.Models;
using System;

namespace SYCH.Controllers
{
    public class IdeasController : Controller
    {
        private ApplicationDbContext _context;

        public IdeasController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Ideas
        public IActionResult Index(string searchString)
        {
            var ideas = from i in _context.Idea
                         select i;
            if (!String.IsNullOrEmpty(searchString))
            {
                ideas = ideas.Where(s => s.Description.Contains(searchString));
            }

            return View(_context.Idea.ToList());
        }

        // GET: Ideas/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Idea idea = _context.Idea.Single(m => m.ID == id);
            if (idea == null)
            {
                return HttpNotFound();
            }

            return View(idea);
        }

        // GET: Ideas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ideas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Idea idea)
        {
            if (ModelState.IsValid)
            {
                _context.Idea.Add(idea);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(idea);
        }

        // GET: Ideas/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Idea idea = _context.Idea.Single(m => m.ID == id);
            if (idea == null)
            {
                return HttpNotFound();
            }
            return View(idea);
        }

        // POST: Ideas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Idea idea)
        {
            if (ModelState.IsValid)
            {
                _context.Update(idea);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(idea);
        }

        // Get Vote
        public IActionResult Vote(int? id)
        {
            Idea idea = _context.Idea.Single(m => m.ID == id);
            return View(idea);
        }

        // POST: Vote up
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Vote(Idea idea)
        {
            if(ModelState.IsValid)
            {
                idea.Votes++;
                idea.Description = idea.Description +"";
                idea.Industry = idea.Industry + "";
                _context.Update(idea);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(idea);
        }

        // GET: Ideas/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Idea idea = _context.Idea.Single(m => m.ID == id);
            if (idea == null)
            {
                return HttpNotFound();
            }

            return View(idea);
        }

        // POST: Ideas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Idea idea = _context.Idea.Single(m => m.ID == id);
            _context.Idea.Remove(idea);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        
    }
}

src/SYCH/Controllers/PremiumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SYCH.Controllers
{
    public class PremiumController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/SYCH/Controllers/ProfilesController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using SYCH.Models;

namespace SYCH.Controllers
{

    public class ProfilesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationDbContext _context;

        public ProfilesController(ApplicationDbContext context)
        {
       
            _context = context;    
        }

        // GET: Profiles
        public ActionResult Index(string filter)
        {
            var profile = from prof in _context.Profile
                          select prof;

            if (!string.IsNullOrEmpty(filter))
            {
                profile = profile.Where(s => s.PositionSeeking.Contains(filter));
            }

            return View(profile);

            //return View(_context.Profile.ToList());
        }
        // GET: Profiles/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Profile profile = _context.Profile.Single(m => m.Id == id);
            if (profile == null)
            {
                return HttpNotFound();
            }

            return View(profile);
        }
        /*
        public IActionResult Search(string filter)
        {
            var profile = from prof in _context.Profile
                         select prof;

            //if (!String.IsNullOrEmpty(filter))
            //{
                profile = profile.Where(s => s.PositionSeeking.Contains(filter));
            //}

            return View(profile);
        }
        */

        // GET: Profiles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Profiles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Profile profile)
        {
            if (ModelState.IsValid)
            {
                _context.Profile.Add(profile);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(profile);
        }

        // GET: Profiles/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Profile profile = _context.Profile.Single(m => m.Id == id);
            if (profile == null)
            {
                return HttpNotFound();
            }
            return View(profile);
        }

        // POST: Profiles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Profile profile)
        {
            if (ModelState.IsValid)
            {
                _context.Update(profile);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(profile);
        }

        // GET: Profiles/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Profile profile = _context.Profile.Single(m => m.Id == id);
            if (profile == null)
            {
                return HttpNotFound();
            }

            return View(profile);
        }

        // POST: Profiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Profile profile = _context.Profile.Single(m => m.Id == id);
            _context.Profile.Remove(profile);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/SYCH/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - SYCH</title>

        <environment names="Development,Staging,Production ">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
            <link rel="stylesheet" href="~/css/site.css" />
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        </environment>
        @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
    </head>
    <body>
        <!-- Nav Bar-->
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">SYCH</a>
                </div>
                <!-- See if user is authenticated-->
@if (User.Identity.IsAuthenticated)
{
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Ideas" asp-action="Index">Ideas</a></li>
                        <li><a asp-controller="Premium" asp-action="Index">Premium</a></li>
                        
                        <li><a asp-controller="Profiles" asp-action="Index">Find Team Members</a></li>
                      
                       
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
}
else
{
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li><a asp-controller="Home" asp-action="Index">Home</a></li>
            <li><a asp-controller="Ideas" asp-action="Index">Ideas</a></li>
            <li><a asp-controller="Premium" asp-action="Index">Premium</a></li>
            
            <li><a asp-controller="Profiles" asp-action="Index">Find Team Members</a></li>
            <li><a asp-controller="FutureIdeas" asp-action="Index">Future Ideas</a></li>

        </ul>
        @await Html.PartialAsync("_LoginPartial")
    </div>

}
            </div>
        </div>
        <div class="body-content">
            @RenderBody()
            <br />
            <div class="box1"></div>
            <center>
                <br />
                <footer>
                    <p>&copy; 2016 - SYCH</p>
                    <a href="mailto:ssych@gmail.com?Subject=Hello%20again" target="_top">CustomerService</a>
                </footer>
                <div class="text-center center-block">
                    
                    <a href="https://www.facebook.com/bootsnipp"><i class="fa fa-facebook-square fa-3x social"></i></a>
                    <a href="https://twitter.com/bootsnipp"><i class="fa fa-twitter-square fa-3x social"></i></a>
                   
                </div>
            </center>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>